# DATASET
train_captions: ../dataset/coco2014/captions_train2014.js>
val_captions: ../dataset/coco2014/captions_val2014.json
train_dir: ../dataset/coco2014/train2014
val_dir: ../dataset/coco2014/val2014

# MODEL
device: cpu
model_text: models/fasttext_wiki.en.bin
model_path: models/best_task_a.pt

# EVALUATION
database_path: results/ft_im2text_db.npy
type: im2text
visualize: True
text_encoder: ft
batch_size: 32