# DATASET
train_captions: /export/home/mcv/datasets/COCO/captions_train2014.js>
val_captions: /export/home/mcv/datasets/COCO/captions_val2014.json
train_dir: /export/home/mcv/datasets/COCO/train2014
val_dir: /export/home/mcv/datasets/COCO/val2014

# MODEL
device: cuda
model_text: /export/home/mcv/m5/fasttext_wiki.en.bin
model_path: /export/home/group02/MCV-M5-Visual-Recognition/week5/models/best_task_c_a_10p.pt

# EVALUATION
database_path: /export/home/group02/MCV-M5-Visual-Recognition/week5/results/bert_db.npy
type: text2image
visualize: False
text_encoder: bert
batch_size: 32