device: cuda
mode: train  # train or evaluate

# DATASET
train_instances: ../dataset/COCO/instances_train2014.json
val_instances: ../dataset/COCO/instances_val2014.json
train_captions: ../dataset/COCO/captions_train2014.json
val_captions: ../dataset/COCO/captions_val2014.json
train_dir: ../dataset/COCO/train2014
val_dir: ../dataset/COCO/val2014

# MODEL
model_text: models/fasttext_wiki.en.bin
embedding_size: 300  # must be 300 if using fasttext

# OPTIMIZER
lr: 0.001
max_lr: 0.01
num_epochs: 10
batch_size: 32