train_instances: "D:/datasets_diskD/annotations/instances_train2014.json"
val_instances: "D:/datasets_diskD/annotations/instances_val2014.json"
train_captions: "D:/datasets_diskD/annotations/captions_train2014.json"
val_captions: "D:/datasets_diskD/annotations/captions_val2014.json"
train_dir: "D:/datasets_diskD/train2014"
val_dir: "D:/datasets_diskD/val2014"