device: "cuda"

train_path: "../dataset/MIT_split/train"
val_path: "../dataset/MIT_split/test"

trunk_path: "models/siamese/trunk_best35.pth"
embedder_path: "models/siamese/embedder_best35.pth"

embedder_size: 256

k_neighbours: 10