device: "cuda"


train_path: "../dataset/COCO/train2014/"
val_path: "../dataset/COCO/val2014/"
train_ann_file: "../dataset/COCO/instances_train2014.json"
val_ann_file: "../dataset/COCO/instances_val2014.json"
mcv_ann: "../dataset/COCO/mcv_image_retrieval_annotations.json"

lr: 0.001
batch_size: 32

num_epochs: 10

embedder_size: 64


