annotations: '../dataset/coco2017/annotations/instances_val2017.json'
# img_path: "../dataset/coco2017/val2017/000000004795.jpg"
# img_path: "../dataset/coco2017/val2017/000000010363.jpg"
# img_path: "../dataset/coco2017/val2017/000000013659.jpg"
img_path: "../dataset/coco2017/val2017/000000094871.jpg"
object_id: 20
object_idx: 2
out_black:
  use: True
out_roi_black:
  use: True
out_black_roi_noise:
  use: True
